version: '3'

services:
  test-image:
    build:
      context: ..
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "6080:6080"
      - "5901:5901"
    labels:
      - "desktop.web.port=6080"
      - "desktop.vnc.port=5901"
    environment:
      - RESOLUTION=1920x1080x16

volumes:
  test-volume:
